### ISSUE TITLE
Setup devnet Generate genesis.json issue

### ISSUE THREAD

**Issue by letspesl** [maticnetwork/matic-cli#60]
After completing npm install according to the guide, an error occurs in a specific process when the following command is executed.
`$ ../bin/matic-cli setup devnet -c ../configs/devnet/docker-setup-config.yaml`
How can I fix it?

<img width="351" alt="image" src="https://user-images.githubusercontent.com/42229322/190574746-bf04bfdf-b094-4879-9a1a-4ed3b2b7d598.png">

```(node:317) UnhandledPromiseRejectionWarning: Error: Command failed: node generate-genesis.js --bor-chain-id 15001 --heimdall-chain-id heimdall-15001
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn solc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

Bor validator set file updated.

    at makeError (/matic-cli/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/matic-cli/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:317) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:317) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by letspesl** [comment]
reinstall solc and fixed issue
